### ISSUE TITLE
Eorror：running ex_csp_motor_imagery.py under the example  folder

### ISSUE THREAD

**Issue by GitHubxiuwen** [breuderink/eegtools#18]
zlib.error: Error -3 while decompressing: invalid distance too far back

Traceback (most recent call last):
  File "E:/BCI/eegtools-master/examples/ex_csp_motor_imagery.py", line 18, in <module>
    d = eegtools.data.bcicomp3_4a.load('aa')
  File "E:\BCI\eegtools-master\eegtools\data\bcicomp3_4a.py", line 79, in load
    tr_mat = StringIO(tr.read('100Hz/data_set_IVa_%s.mat' % subject))  
  File "C:\Anaconda3\envs\py27\lib\zipfile.py", line 938, in read
    return self.open(name, "r", pwd).read()
  File "C:\Anaconda3\envs\py27\lib\zipfile.py", line 630, in read
    data = self.read1(n)
  File "C:\Anaconda3\envs\py27\lib\zipfile.py", line 684, in read1
    max(n - len_readbuffer, self.MIN_READ_SIZE)
zlib.error: Error -3 while decompressing: invalid distance too far back

**Comment by breuderink** [comment]
It seems like the zip file is corrupt. Can you retry downloading the file? Perhaps by removing the `~/eegtools_data` dir?

**Comment by breuderink** [comment]
Just confirmed the issue, see #19.
